# Generated by Django 4.0.2 on 2022-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.TextField(choices=[('N', 'Normal'), ('S', 'Sick Leave')]),
        ),
    ]
