# Generated by Django 4.0.2 on 2022-02-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_app', '0002_alter_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(choices=[('N', 'Normal'), ('S', 'Sick Leave')]),
        ),
    ]
